### ISSUE TITLE
jtlabrun.bin is missing (png is there)

### ISSUE THREAD

**Issue by AnotherPocket** [dyreschlock/pocket-platform-images#34]
Hi. I just replaced my JTCore images with your collection. I was unable to add jtlabrun.bin, because I could not find it. Did I miss it or is it missing? Thank you!

**Comment by dyreschlock** [comment]
Ah, you're right.  Looks like jtlabrun snuck its way into the home releases

**Comment by dyreschlock** [comment]
Alrighty.  This has been fixed, and a new release has been published :)
